
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info

proxies:
  - name: "MySOCKS5"
    type: socks5
    server: 217.177.34.19
    port: 6012
    username: eyvizq4mf8n3
    password: 6jo0C8dNSfrtkclt
    udp: true

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "MySOCKS5"
      - DIRECT

rules:
  - MATCH,Proxy

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 9.9.9.9
    - 8.8.4.4
